src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"login"}, message="Аккаунт с указанным логином уже существует")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $login;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $patronymic;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToOne(targetEntity=Client::class, mappedBy="account", cascade={"persist", "remove"})
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=Checkup::class, mappedBy="doctor")
     */
    private $checkups;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="registrar")
     */
    private $payments;

    public function __construct()
    {
        $this->checkups = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->login;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername()
    {
        return $this->lastName . ' ' . $this->firstName;
    }

    public function getFullName()
    {
        return $this->lastName . ' ' . $this->firstName . ' ' . $this->patronymic;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPatronymic(): ?string
    {
        return $this->patronymic;
    }

    public function setPatronymic(?string $patronymic): self
    {
        $this->patronymic = $patronymic;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        if ($client->getAccount() !== $this) {
            $client->setAccount($this);
        }

        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|Checkup[]
     */
    public function getCheckups(): Collection
    {
        return $this->checkups;
    }

    public function addCheckup(Checkup $checkup): self
    {
        if (!$this->checkups->contains($checkup)) {
            $this->checkups[] = $checkup;
            $checkup->setDoctor($this);
        }

        return $this;
    }

    public function getCheckupsSum()
    {
        $sum = 0;
        foreach ($this->checkups as $checkup) {
            $sum += $checkup->calculateSum();
        }
        return $sum;
    }

    public function removeCheckup(Checkup $checkup): self
    {
        if ($this->checkups->removeElement($checkup)) {
            if ($checkup->getDoctor() === $this) {
                $checkup->setDoctor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setRegistrar($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            if ($payment->getRegistrar() === $this) {
                $payment->setRegistrar(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->login;
    }
}

src/Form/CheckupType.php
<?php

namespace App\Form;

use App\Entity\Checkup;
use App\Entity\Pet;
use App\Entity\User;
use App\Service\CheckupDateService;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

class CheckupType extends AbstractType
{
    private $security;
    private $checkupDateService;

    public function __construct(Security $security, CheckupDateService $checkupDateService)
    {
        $this->security = $security;
        $this->checkupDateService = $checkupDateService;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pet', EntityType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Вы должны выбрать Животное! Если его нет в списке, то Вы всегда можете добавить его в личном кабинете',
                    ]),
                ],
                'class' => Pet::class,
                'query_builder' => function (EntityRepository $entityManager) {
                    return $entityManager->createQueryBuilder('p')
                        ->andWhere('p.owner = :owner')
                        ->setParameter('owner', $this->security->getUser()->getClient())
                        ->andWhere('p.status = true')
                        ->orderBy('p.name', 'ASC')
                        ;
                },
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'form-select',
                ],
            ])
            ->add('doctor', EntityType::class, [
                'class' => User::class,
                'query_builder' => function (EntityRepository $entityManager) {
                    return $entityManager->createQueryBuilder('u')
                        ->andWhere('CAST(u.roles as text) = \'["ROLE_DOCTOR"]\'')
                        ->orderBy('u.lastName', 'ASC')
                        ->orderBy('u.firstName', 'ASC')
                        ->orderBy('u.patronymic', 'ASC')
                        ;
                },
                'choice_label' => 'fullName',
                'attr' => [
                    'class' => 'form-select',
                ],
            ])
            ->add('date', DateType::class, [
                'constraints' => [
                    new Callback(function ($object, ExecutionContextInterface $context) {
                        $now = new \DateTime((new \DateTime('now'))->format('Y-m-d'));
                        $current = $object;
                        $lastCheckupTime = new \DateTime($current->format('Y-m-d') . ' 16:30');
                        if ($current->format('U') - $now->format('U') < 0) {
                            if (0 === $current->format('U') - (new \DateTime('1970-01-01 11:11:11'))->format('U')) {
                                $context
                                    ->buildViolation('На сегодня не осталось мест')
                                    ->addViolation();
                            } else {
                                $context
                                    ->buildViolation('Приём не может быть назначен на прошедшую дату')
                                    ->addViolation();
                            }
                        } elseif ($lastCheckupTime->format('U') - (new \DateTime())->format('U') < 0) {
                            $context
                                ->buildViolation('На сегодня приёмы завершены')
                                ->addViolation();
                        }
                    }),
                ],
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-select',
                ],
            ])
        ;
        $builder->get('date')
            ->addModelTransformer(new CallbackTransformer(
                function () {
                    return new \DateTime();
                },
                function ($date) {
                    return $this->checkupDateService->getNextDate($date);
                }
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Checkup::class,
        ]);
    }
}

src/Controller/CheckupController.php
<?php

namespace App\Controller;

use App\Entity\Checkup;
use App\Entity\Payment;
use App\Form\CheckupType;
use App\Repository\CheckupRepository;
use App\Service\PublisherAMQP;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/checkup")
 */
class CheckupController extends AbstractController
{
    /**
     * @Route("/new", name="checkup_new", methods={"GET","POST"})
     */
    public function new(Request $request, PublisherAMQP $publisherAMQP): Response
    {
        $checkup = new Checkup();
        $checkup->setStatus('Назначен');
        $form = $this->createForm(CheckupType::class, $checkup);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($checkup);
            $entityManager->flush();

            $checkupDto[] = [
                'id' => $checkup->getId(),
                'client_name' => $checkup->getPet()->getOwner()->getAccount()->getFullName(),
                'pet_name' => $checkup->getPet()->getName(),
                'pet_kind' => $checkup->getPet()->getKind()->getName(),
                'pet_sex' => $checkup->getPet()->getSex() ? 'Мужской' : 'Женский',
                'checkup_date' => $checkup->getDate()->format('c'),
            ];
            $amqpMessage = [
                'action' => 'add',
                'payload' => $checkupDto,
            ];
            // $publisherAMQP->publishMessage(json_encode($amqpMessage));

            return $this->redirectToRoute('client_checkups');
        }

        return $this->render('checkup/new.html.twig', [
            'checkup' => $checkup,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/pay/{id}", name="checkup_pay", methods={"GET","POST"})
     */
    public function checkupPay(
        CheckupRepository $checkupRepository,
        EntityManagerInterface $manager,
        int $id
    ): Response {
        $checkup = $checkupRepository->find($id);
        if ($checkup) {
            $checkup->setStatus('Оплачен');
            $manager->persist($checkup);
            $payment = new Payment();
            $payment->setCheckup($checkup);
            $payment->setClient($checkup->getPet()->getOwner());
            $payment->setSum($checkup->calculateSum());
            $payment->setDate(new \DateTime());
            $payment->setStatus('Ожидает подтверждения');
            $manager->persist($payment);
            $manager->flush();
        }

        return $this->redirectToRoute('client_checkups');
    }

    /**
     * @Route("/cancel/{id}", name="checkup_cancel", methods={"GET","POST"})
     */
    public function checkupCancel(
        PublisherAMQP $publisherAMQP,
        CheckupRepository $checkupRepository,
        EntityManagerInterface $manager,
        int $id
    ): Response {
        $checkup = $checkupRepository->find($id);
        if ($checkup) {
            $checkup->setStatus('Отменён');
            $manager->persist($checkup);
            $manager->flush();

            $amqpMessage = [
                'action' => 'cancel',
                'id' => $checkup->getId(),
                'date' => $checkup->getDate()->format('c'),
            ];
            // $publisherAMQP->publishMessage(json_encode($amqpMessage));
        }

        return $this->redirectToRoute('client_checkups');
    }
}

templates/checkup/doctor.html.twig
{% extends 'base.html.twig' %}

{% block title %}VetClinic | Назначенные приёмы {% endblock %}

{% block profile %}
{% endblock %}

{% block content %}
    <!-- Services start -->
    <div class="row main__row d-flex justify-content-center">
        <main class="col-md-10 ml-sm-auto col-lg-10 px-4 bg-white rounded shadow" role="main">
            <div class="home">
                <div class="wrapper">
                    <div class="home__info">
                        <h1 class="block-header text-center">
                            Список назначенных приёмов
                        </h1>
                    </div>
                </div>
                <table class="table table-hover text-center">
                    <thead class="topic-table__header">
                    <tr>
                        <th scope="col">Клиент</th>
                        <th scope="col">Животное</th>
                        <th scope="col">Дата приёма</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody class="topic-table__content">
                    {% for checkup in pagination %}
                        <tr>
                            <td>{{ checkup.pet.owner.account.fullName }}</td>
                            <td>{{ checkup.pet.name }}</td>
                            <td>{{ checkup.date|date('d.m.Y H:i')  }}</td>
                            {% if checkup.status is same as 'Назначен' %}
                                <td><a href="{{ path('checkup_edit', { id: checkup.id }) }}" onclick="return confirm('Вы действительно хотите провести данный приём?')" class="btn">Провести приём</a></td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="navigation paginator__text">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
        </main>
    </div>
    <!-- Services end -->
{% endblock %}

templates/checkup/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}VetClinic | Проведение приёма{% endblock %}

{% block profile %}
{% endblock %}

{% block content %}
    <!-- Checkup form start -->
    <div class="row main__row d-flex justify-content-center">
        <main class="col-md-10 ml-sm-auto col-lg-10 px-4 bg-white rounded shadow" role="main">
            <div class="home">
                <div class="wrapper">
                    <div class="home__info">
                        <h1 class="block-header text-center">
                            Проведение приёма
                        </h1>
                    </div>
                </div>
                <div class="content">
                    {{ form_start(form) }}
                    {% set formErrors = form.vars.errors.form.getErrors(true) %}
                    {% if formErrors|length %}
                        <div class="user-details">
                            <ul>
                                {% for error in formErrors %}
                                    <li class="register-errors">
                                        ● {{ error.message }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                    <div class="new-topic-details">
                        <div class="input-box">
                            <span class="details">Жалобы</span>
                            {{ form_widget(form.complaints) }}
                        </div>
                        <div class="input-box">
                            <span class="details">Диагноз</span>
                            {{ form_widget(form.diagnosis) }}
                        </div>
                        <div class="input-box">
                            <span class="details">Лечение</span>
                            {{ form_widget(form.treatment) }}
                        </div>
                        <div class="input-box">
                            <span class="details">Оказанные услуги</span>
                            {{ form_widget(form.services) }}
                        </div>
                    </div>
                    <div class="button">
                        <input type="submit" value="Завершить приём">
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </main>
    </div>
    <!-- Checkup form end -->
{% endblock %}

templates/checkup/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}VetClinic | Оплаченные приёмы {% endblock %}

{% block profile %}
{% endblock %}

{% block content %}
    <!-- Services start -->
    <div class="row main__row d-flex justify-content-center">
        <main class="col-md-10 ml-sm-auto col-lg-10 px-4 bg-white rounded shadow" role="main">
            <div class="home">
                <div class="wrapper">
                    <div class="home__info">
                        <h1 class="block-header text-center">
                            Список оплаченных приёмов
                        </h1>
                    </div>
                </div>
                <table class="table table-hover text-center">
                    <thead class="topic-table__header">
                    <tr>
                        <th scope="col">Клиент</th>
                        <th scope="col">Питомец</th>
                        <th scope="col">Доктор</th>
                        <th scope="col">Дата приёма</th>
                        <th scope="col">Статус</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody class="topic-table__content">
                    {% for checkup in pagination %}
                        <tr>
                            <td>{{ checkup.pet.owner.account.fullName }}</td>
                            <td>{{ checkup.pet.name }}</td>
                            <td>{{ checkup.doctor.username }}</td>
                            <td>{{ checkup.date|date('d.m.Y H:i')  }}</td>
                            <td>{{ checkup.status }}</td>
                            {% if checkup.status is same as 'Оплачен' %}
                                <td><a href="{{ path('checkup_close', { id: checkup.id }) }}" onclick="return confirm('Вы действительно хотите подтвердить оплату данного приёма?')" class="btn">Подтвердить</a></td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="navigation paginator__text">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
        </main>
    </div>
    <!-- Services end -->
{% endblock %}

templates/checkup/new.html.twig
{% extends 'profile/index.html.twig' %}

{% block title %}VetClinic | Запись на приём{% endblock %}

{% block content %}
    <!-- New checkup form start -->
    <div class="container">
        <div class="title">Запись на приём</div>
        <div class="content">
            {{ form_start(form) }}
            {% set formErrors = form.vars.errors.form.getErrors(true) %}
            {% if formErrors|length %}
                <div class="user-details">
                    <ul>
                        {% for error in formErrors %}
                            <li class="register-errors">
                                ● {{ error.message }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <div class="user-details">
                <div class="input-box">
                    <span class="details">Выберите животное</span>
                    {{ form_widget(form.pet) }}
                </div>
                <div class="input-box">
                    <span class="details">Выберите доктора</span>
                    {{ form_widget(form.doctor) }}
                </div>
                <div class="input-box">
                    <span class="details">Выберите время</span>
                    {{ form_widget(form.date) }}
                </div>
            </div>
            <div class="button">
                <input type="submit" value="Записаться">
            </div>
            {{ form_end(form) }}
        </div>
    </div>
    <!-- New checkup form end -->
{% endblock %}

templates/checkup/registrar.html.twig
{% extends 'base.html.twig' %}

{% block title %}VetClinic | Оплаченные приёмы {% endblock %}

{% block profile %}
{% endblock %}

{% block content %}
    <!-- Services start -->
    <div class="row main__row d-flex justify-content-center">
        <main class="col-md-10 ml-sm-auto col-lg-10 px-4 bg-white rounded" role="main">
            <div class="home">
                <div class="wrapper">
                    <div class="home__info">
                        <h1 class="block-header text-center">
                            Список оплаченных приёмов
                        </h1>
                    </div>
                </div>
                <table class="table table-hover text-center">
                    <thead class="topic-table__header">
                    <tr>
                        <th scope="col">Клиент</th>
                        <th scope="col">Животное</th>
                        <th scope="col">Доктор</th>
                        <th scope="col">Дата приёма</th>
                        <th scope="col">Статус</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody class="topic-table__content">
                    {% for checkup in pagination %}
                        <tr>
                            <td>{{ checkup.pet.owner.account.fullName }}</td>
                            <td>{{ checkup.pet.name }}</td>
                            <td>{{ checkup.doctor.username }}</td>
                            <td>{{ checkup.date|date('d.m.Y H:i')  }}</td>
                            <td>{{ checkup.status }}</td>
                            {% if checkup.status is same as 'Оплачен' %}
                                <td><a href="{{ path('checkup_close', { id: checkup.id }) }}" onclick="return confirm('Вы действительно хотите подтвердить оплату данного приёма?')" class="btn">Подтвердить</a></td>
                            {% else %}
                                <td></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="navigation paginator__text">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
        </main>
    </div>
    <!-- Services end -->
{% endblock %}