src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @UniqueEntity(fields={"login"}, message="Аккаунт с указанным логином уже существует")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $login;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $patronymic;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToOne(targetEntity=Client::class, mappedBy="account", cascade={"persist", "remove"})
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=Checkup::class, mappedBy="doctor")
     */
    private $checkups;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="registrar")
     */
    private $payments;

    public function __construct()
    {
        $this->checkups = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->login;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername()
    {
        return $this->lastName . ' ' . $this->firstName;
    }

    public function getFullName()
    {
        return $this->lastName . ' ' . $this->firstName . ' ' . $this->patronymic;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPatronymic(): ?string
    {
        return $this->patronymic;
    }

    public function setPatronymic(?string $patronymic): self
    {
        $this->patronymic = $patronymic;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(Client $client): self
    {
        if ($client->getAccount() !== $this) {
            $client->setAccount($this);
        }

        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|Checkup[]
     */
    public function getCheckups(): Collection
    {
        return $this->checkups;
    }

    public function addCheckup(Checkup $checkup): self
    {
        if (!$this->checkups->contains($checkup)) {
            $this->checkups[] = $checkup;
            $checkup->setDoctor($this);
        }

        return $this;
    }

    public function getCheckupsSum()
    {
        $sum = 0;
        foreach ($this->checkups as $checkup) {
            $sum += $checkup->calculateSum();
        }
        return $sum;
    }

    public function removeCheckup(Checkup $checkup): self
    {
        if ($this->checkups->removeElement($checkup)) {
            if ($checkup->getDoctor() === $this) {
                $checkup->setDoctor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Payment[]
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): self
    {
        if (!$this->payments->contains($payment)) {
            $this->payments[] = $payment;
            $payment->setRegistrar($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): self
    {
        if ($this->payments->removeElement($payment)) {
            if ($payment->getRegistrar() === $this) {
                $payment->setRegistrar(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->login;
    }
}

src/Controller/ReportController.php
<?php

namespace App\Controller;

use App\Repository\ServiceRepository;
use App\Repository\UserRepository;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/report")
 */
class ReportController extends AbstractController
{
    /**
     * @Route("/services", name="report_services")
     */
    public function reportServices(ServiceRepository $serviceRepository, Pdf $knpSnappyPdf)
    {
        $services = $serviceRepository->getServicesPaginationQuery()->getResult();
        $html = $this->renderView('report/services.html.twig', [
            'services' => $services,
        ]);

        return new PdfResponse(
            $knpSnappyPdf->getOutputFromHtml($html),
            'Services.pdf'
        );
    }

    /**
     * @Route("/doctors", name="report_doctors")
     */
    public function reportDoctors(UserRepository $userRepository, Pdf $knpSnappyPdf)
    {
        $doctors = $userRepository->getDoctors();
        $html = $this->renderView('report/doctors.html.twig', [
            'doctors' => $doctors,
        ]);

        return new PdfResponse(
            $knpSnappyPdf->getOutputFromHtml($html),
            'Doctors.pdf'
        );
    }
}

templates/report/doctors.html.twig
{% extends 'report.html.twig' %}

{% block title %}VetClinic | Список докторов {% endblock %}

{% block content %}
    <!-- Services start -->
    <div class="row main__row d-flex justify-content-center">
        <main class="col-md-10 ml-sm-auto col-lg-10 px-4 bg-white rounded shadow" role="main">
            <div class="home">
                <div class="wrapper">
                    <div class="home__info">
                        <h1 class="block-header text-center">
                            Список докторов
                        </h1>
                    </div>
                </div>
                <table class="table table-hover text-center">
                    <thead class="topic-table__header">
                    <tr>
                        <th scope="col">ФИО доктора</th>
                        <th scope="col">Количество приёмов</th>
                        <th scope="col">Сумма</th>
                    </tr>
                    </thead>
                    <tbody class="topic-table__content">
                    {% for doctor in doctors %}
                        <tr>
                            <td>{{ doctor.fullName }}</td>
                            <td>{{ doctor.checkups.count }}</td>
                            <td>{{ doctor.getCheckupsSum() }} р.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </div>
    <!-- Services end -->
{% endblock %}

templates/report/services.html.twig
{% extends 'report.html.twig' %}

{% block title %}VetClinic | Список услуг {% endblock %}

{% block content %}
    <!-- Services start -->
    <div class="row main__row d-flex justify-content-center">
        <main class="col-md-10 ml-sm-auto col-lg-10 px-4 bg-white rounded shadow" role="main">
            <div class="home">
                <div class="wrapper">
                    <div class="home__info">
                        <h1 class="block-header text-center">
                            Список предоставляемых услуг
                        </h1>
                    </div>
                </div>
                <table class="table table-hover text-center">
                    <thead class="topic-table__header">
                    <tr>
                        <th scope="col">Название услуги</th>
                        <th scope="col">Цена услуги</th>
                    </tr>
                    </thead>
                    <tbody class="topic-table__content">
                    {% for service in services %}
                        <tr>
                            <td>{{ service.name }}</td>
                            <td>{{ service.price }} р.</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </div>
    <!-- Services end -->
{% endblock %}